// lib/dealers/data.ts
import { Dealer } from "@/types/dealer";

// Static fallback data — used when Supabase is unavailable.
// Authoritative data lives in the `dealers` table in Supabase.
export const dealers: Dealer[] = [
  {
    id: "1",
    dealer_name: "Gentech Guard Mumbai Central",
    contact_person: "Rajesh Sharma",
    phone: "+91 99898 20222",
    email: "mumbai@gentechguard.com",
    address: "123 Marine Drive, Near Oberoi Mall",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400002",
    latitude: 19.076,
    longitude: 72.878,
    is_active: true,
    dealer_type: "premium",
    created_at: "2024-01-15"
  },
  {
    id: "2",
    dealer_name: "Delhi Premium Auto Care",
    contact_person: "Vikram Singh",
    phone: "+91 99898 20223",
    email: "delhi@gentechguard.com",
    address: "456 Connaught Place, New Delhi",
    city: "Delhi",
    state: "Delhi",
    pincode: "110001",
    latitude: 28.614,
    longitude: 77.209,
    is_active: true,
    dealer_type: "premium",
    created_at: "2024-01-20"
  },
  {
    id: "3",
    dealer_name: "Bangalore South PPF Center",
    contact_person: "Priya Kumar",
    phone: "+91 99898 20224",
    email: "bangalore@gentechguard.com",
    address: "789 Koramangala, Bangalore",
    city: "Bangalore",
    state: "Karnataka",
    pincode: "560034",
    latitude: 12.972,
    longitude: 77.594,
    is_active: true,
    dealer_type: "premium",
    created_at: "2024-02-01"
  },
  {
    id: "4",
    dealer_name: "Hyderabad Auto Shield",
    contact_person: "Suresh Reddy",
    phone: "+91 99898 20225",
    email: "hyderabad@gentechguard.com",
    address: "321 Banjara Hills, Hyderabad",
    city: "Hyderabad",
    state: "Telangana",
    pincode: "500034",
    latitude: 17.385,
    longitude: 78.486,
    is_active: true,
    dealer_type: "premium",
    created_at: "2024-02-10"
  },
  {
    id: "5",
    dealer_name: "Chennai Coastal Protection",
    contact_person: "Karthik Venkat",
    phone: "+91 99898 20226",
    email: "chennai@gentechguard.com",
    address: "654 Anna Salai, Chennai",
    city: "Chennai",
    state: "Tamil Nadu",
    pincode: "600002",
    latitude: 13.083,
    longitude: 80.270,
    is_active: true,
    dealer_type: "standard",
    created_at: "2024-02-15"
  },
  {
    id: "6",
    dealer_name: "Kolkata East Auto Films",
    contact_person: "Arjun Banerjee",
    phone: "+91 99898 20227",
    email: "kolkata@gentechguard.com",
    address: "987 Park Street, Kolkata",
    city: "Kolkata",
    state: "West Bengal",
    pincode: "700016",
    latitude: 22.572,
    longitude: 88.364,
    is_active: true,
    dealer_type: "standard",
    created_at: "2024-02-20"
  },
  {
    id: "7",
    dealer_name: "Pune West Auto Care",
    contact_person: "Amit Patil",
    phone: "+91 99898 20228",
    email: "pune@gentechguard.com",
    address: "147 FC Road, Pune",
    city: "Pune",
    state: "Maharashtra",
    pincode: "411004",
    latitude: 18.520,
    longitude: 73.856,
    is_active: true,
    dealer_type: "standard",
    created_at: "2024-03-01"
  },
  {
    id: "8",
    dealer_name: "Ahmedabad Gujarat Auto Shield",
    contact_person: "Naresh Patel",
    phone: "+91 99898 20229",
    email: "ahmedabad@gentechguard.com",
    address: "258 CG Road, Ahmedabad",
    city: "Ahmedabad",
    state: "Gujarat",
    pincode: "380009",
    latitude: 23.023,
    longitude: 72.571,
    is_active: true,
    dealer_type: "standard",
    created_at: "2024-03-05"
  },
  {
    id: "9",
    dealer_name: "Jaipur Royal Auto Protection",
    contact_person: "Rajendra Singh",
    phone: "+91 99898 20230",
    email: "jaipur@gentechguard.com",
    address: "369 MI Road, Jaipur",
    city: "Jaipur",
    state: "Rajasthan",
    pincode: "302001",
    latitude: 26.912,
    longitude: 75.787,
    is_active: true,
    dealer_type: "standard",
    created_at: "2024-03-10"
  },
  {
    id: "10",
    dealer_name: "Kochi Kerala Auto Films",
    contact_person: "Thomas George",
    phone: "+91 99898 20231",
    email: "kochi@gentechguard.com",
    address: "741 MG Road, Kochi",
    city: "Kochi",
    state: "Kerala",
    pincode: "682011",
    latitude: 9.932,
    longitude: 76.267,
    is_active: true,
    dealer_type: "standard",
    created_at: "2024-03-15"
  },
  {
    id: "11",
    dealer_name: "Chandigarh North Auto Care",
    contact_person: "Harpreet Singh",
    phone: "+91 99898 20232",
    email: "chandigarh@gentechguard.com",
    address: "852 Sector 17, Chandigarh",
    city: "Chandigarh",
    state: "Chandigarh",
    pincode: "160017",
    latitude: 30.734,
    longitude: 76.779,
    is_active: true,
    dealer_type: "standard",
    created_at: "2024-03-20"
  },
  {
    id: "12",
    dealer_name: "Lucknow UP Auto Shield",
    contact_person: "Amitabh Tiwari",
    phone: "+91 99898 20233",
    email: "lucknow@gentechguard.com",
    address: "963 Hazratganj, Lucknow",
    city: "Lucknow",
    state: "Uttar Pradesh",
    pincode: "226001",
    latitude: 26.847,
    longitude: 80.947,
    is_active: true,
    dealer_type: "standard",
    created_at: "2024-03-25"
  },
  {
    id: "13",
    dealer_name: "Bhopal MP Protection Center",
    contact_person: "Rahul Verma",
    phone: "+91 99898 20234",
    email: "bhopal@gentechguard.com",
    address: "159 MP Nagar, Bhopal",
    city: "Bhopal",
    state: "Madhya Pradesh",
    pincode: "462011",
    latitude: 23.260,
    longitude: 77.413,
    is_active: true,
    dealer_type: "standard",
    created_at: "2024-04-01"
  },
  {
    id: "14",
    dealer_name: "Visakhapatnam AP Films",
    contact_person: "Srinivas Rao",
    phone: "+91 99898 20235",
    email: "vizag@gentechguard.com",
    address: "357 Beach Road, Visakhapatnam",
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    pincode: "530002",
    latitude: 17.686,
    longitude: 83.218,
    is_active: true,
    dealer_type: "coming_soon",
    created_at: "2024-04-05"
  },
  {
    id: "15",
    dealer_name: "Indore Premium Auto Care",
    contact_person: "Neeraj Gupta",
    phone: "+91 99898 20236",
    email: "indore@gentechguard.com",
    address: "753 MG Road, Indore",
    city: "Indore",
    state: "Madhya Pradesh",
    pincode: "452001",
    latitude: 22.720,
    longitude: 75.857,
    is_active: true,
    dealer_type: "standard",
    created_at: "2024-04-10"
  }
];

export const getDealerStats = (dealerList: Dealer[] = dealers) => {
  const activeDealers = dealerList.filter(d => d.is_active);
  return {
    total: activeDealers.length,
    premium: activeDealers.filter(d => d.dealer_type === 'premium').length,
    standard: activeDealers.filter(d => d.dealer_type === 'standard').length,
    comingSoon: activeDealers.filter(d => d.dealer_type === 'coming_soon').length,
    cities: new Set(activeDealers.map(d => d.city)).size,
    states: new Set(activeDealers.map(d => d.state)).size
  };
};
